-- 코드를 입력하세요
SELECT UGB.TITLE,
       UGB.BOARD_ID,
       UGR.REPLY_ID,
       UGR.WRITER_ID,
       UGR.CONTENTS,
       TO_CHAR(UGR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
  FROM USED_GOODS_BOARD UGB,
       USED_GOODS_REPLY UGR
 WHERE UGB.BOARD_ID = UGR.BOARD_ID
   AND UGB.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
   AND UGB.CREATED_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
 ORDER BY UGR.CREATED_DATE, UGB.TITLE